### PR TITLE
implement a Python script + calling shell script to update RAT manufacturer with merging removed manufacturers back in with active=false

### PR DESCRIPTION
**Pull request by dslmeinte**
As discussed in https://github.com/ehn-dcc-development/ehn-dcc-valuesets/pull/2.

The current `test-manf.json` has just been sorted, but not been updated yet.
Running `sh source-update/merge-rat.sh` will cause a diff, which is to be committed separately.

### CODE REVIEW

**Review by kruzikh — CHANGES_REQUESTED** [review]
I see two potential problems:
1. we need to add date and time when RAT test has been removed from common list and store that date (timestamp of the change of the status to inactive) into the version element.
2. Update version information only for entries that had been "recently" removed from common list (were previously active).

**Comment by gabywh** [comment]
@kruzikh versioning: was there ever a final decision on versioning of each of the valuesets rather than each of the entries within them (and/or do we keep same version for *all* valuesets - would imply script automation in place for all)? Simplest is date-time stamp to nearest second. Almost tempted to use `date +s%` for this since we just want some idea of an incremental value and we assume UTC for versioning. Does mean the script would need to be consistently run on *nix environment - possible maintenance issue in the future - or we just go, once again, for ISO 8601 date-time to nearest second based on UTC .

Unless you can propose an agreed alternative?

**Comment by kruzikh** [comment]
@gabywh re versionning: At this moment we keep version information at the entry level of each value set.  We also have date information (of last update) at the value set level. In case of inactivated entries (like in RAT list) we need to trace date and time, when the entry has been inactivated/re-activated. Because we cannot change json schema of the value sets, it has been discussed that we can abuse version element to stare this information. I think that precision to a minute or hour will be sufficient. In order to achieve this, for now (until we will have a precise information from RAT API), we should run the update-rat script e.g. every hour.

**Comment by dslmeinte** [comment]
@kruzikh @gabywh Why introduce a new timestamp value (either for the `version` field of an individual value set value, or for the `valueSetDate` of a value set as whole)? Inactivated values could get `active` set tot `false`, and `version` to the value set-global timestamp to indicate from when on that value was inactive. For active values: only update `version` when something actually changed?

By the way: I just re-ran the `merge-rat.sh` script, and noticed that apparently values can be reactivated as well: two values that were inactivated during the previous run (see https://github.com/ehn-dcc-development/ehn-dcc-valuesets/blob/update-rat-20210625/test-manf.json#L554; ids are: 1246, 1256) are now active again. What do we make of that?

**Pull request closed without merging**
