### PR TITLE
New changes according to the guidelines v1.2

### PR DESCRIPTION
**Pull request by kruzikh**
Changes of the DCC value sets as decided by the eHN:
1. adds new entry in vaccine-mah-manf value set: Serum Institute of India
2. changes to vaccine-medicinal-product value set:
- COVID-19 Vaccine Moderna renamed to Spikevax
- adds Covishield

### CODE REVIEW

**Comment by skounis** [comment]
Version `1.0` is there for some entries but not all. Is this intentional?

**Review by gabywh — CHANGES_REQUESTED** [review]
Contents ok, but PR description too vague:
"Changes of the vaccine-medicinal-product and vaccine manufacturer value set as decided by the eHN last week." tells me very little and last week is rather movable as a date ;)

Sth like:
"adds Serum Institute of India and Covishield, update Moderna vaccine name to Spikevax"
would tell me a lot more, but I will leave the final wording up to you -> essentially think of this text as: "what would be helpful in a release note describing the changes?"

**Comment by kruzikh** [comment]
Sorry @gabywh for slow reaction. I am on vacations and reading e-mails only occasionally. We should discuss how to make change management process more agile and robust. We should specify a concrete group of people that will act as a team with shared responsibility for updates of the value sets on Github. It is still too wage and as recent case shown:
1. it is not clear how and by whom we will be informed if eHN decides on any change of the value set
2. It is not clear how the group will distribute the work on implementation of the change and verification of the change before publication
3. and finally it is not yet clear how this change will be communicated to TSI for implementation into the DCCG. Maybe this step could be automated?

What do you think? And BTW some changes of the value sets might trigger the need to change business rues and M/S should be also officially informed about any change.

Best regards
Hynek

**Comment by kruzikh** [comment]
> Version `1.0` is there for some entries but not all. Is this intentional?

Hi @skounis,
yes it is, we took version information from the coding system. In some cases, maintainers does not assign version information (such as EMA or JRC). We assigned version 1.0 to the entries that are being maintained solely by SGS as its own coding system.

**Comment by gabywh** [comment]
> Sorry @gabywh for slow reaction.

no problem

> I am on vacations 

no way... what's vacation anyway? ;)

> and reading e-mails only occasionally. 

tut tut... if I was your wife I'd take your laptop / tablet / mobile away from you and tell you that you're on vacation !!! ;)

> We should discuss how to make change management process more agile and robust. 

We should indeed - was tentatively suggested early next week? Only difficulty I have is how to make sth more agile and robust that doesn't yet exist ;) I've been doing change management for decades, also agile, so I have some ideas...

> We should specify a concrete group of people 

We should specify the responsibilties (done, I think, with the Tech IOP / Vincent spreadsheet ?) and then identify the * roles * required.

Once we have the roles, fill them with at least two people (who are hopefully not concrete but alive and well ;) so we have cover for when one of them goes and does sth strange -  like go on vacation... ;)

> that will act as a team with shared responsibility for updates of the value sets on Github.

Indeed, as above.

> It is still too wage 

I didn't think it was ever fully defined at all, never mind being vague...!

> and as recent case shown:
> 
> 1. it is not clear how and by whom we will be informed if eHN decides on any change of the value set
> 2. It is not clear how the group will distribute the work on implementation of the change and verification of the change before publication
> 3. and finally it is not yet clear how this change will be communicated to TSI for implementation into the DCCG. Maybe this step could be automated?
> 
> What do you think? 

I think it's not clear because it's not defined at all :) Thus cause-effect established and now we can all go home .... 

Lol, no, as above: once we have the responsibilities and process in place, the roles fall out of that and then we fill them with bodies to actually do stuff. We could probably go for a RACI chart (e.g. https://racichart.org/) even though they seem to be less trendy nowadays for whatever reason. Love this quote from that link, BTW:

> Notice also how a RACI chart encourages strong communication between team members with the Informed and Consulted roles.  In the hectic environment that most businesses operate in, this communication will oftentimes be neglected without a tool like RACI.

I'm saying nothing ;)

> And BTW some changes of the value sets might trigger the need to change business rues and M/S should be also officially informed about any change.

Absolutely - all part of the process, dear chap.

> 
> Best regards
> Hynek

... and even if I'm not your wife: now go and shut your laptop and enjoy your well-earned vacation !!!

Gaby.

**Comment by gabywh** [comment]
> tut tut... if I was your wife I'd ...

... which always reminds me of a quote attributed to the British Prime Minister Churchill during a debate in the House of Commons:

Member of Parliament: "Sir, if I was your wife, I'd poison your coffee !"
Churchill: "Madam, if you were my wife, I'd drink it !"

Now go enjoy your vacation :)
Gaby.

**Review by ryanbnl — APPROVED** [review]

**Review by gabywh — APPROVED** [review]

**Pull request merged**
