### PR TITLE
sort RAT manufacturers by ID to be able to better compare diffs

### PR DESCRIPTION
**Pull request by dslmeinte**
Sort the RAT manufacturers by ID so that diffs understand better what really changed in `test-manf.json`.

`test-manf.json` sorted with the `jq` expression `'{ "valueSetId": .valueSetId, "valueSetDate": .valueSetDate, "valueSetValues": .valueSetValues|to_entries|sort_by(.key | tonumber)|from_entries }'`

### CODE REVIEW

**Comment by kruzikh** [comment]
This is useful indeed for manual comparison, however I just have sent a request to Konstantin to ask JRC to change their API. My proposal to JRC is following:
1. To include also RAT tests which has been present and later removed from HSC common recognition list
2. To change data type of the element hsc-list-history.list-date to a timestamp
3. To record date of the removal from HSC common list in the hsc-list-history.list-date element

Shouldn't we wait for the answer?

**Review by kruzikh — APPROVED** [review]

**Comment by dslmeinte** [comment]
@kruzikh 👍 for requesting the JRC API change.

No problem waiting a bit, but I like to have a Plan B ready, for when the API change doesn't come through. And when it does, it'd still make sense to sort the values by id, to make the derivation as stable as possible.

**Comment by gabywh** [comment]
> @kruzikh  for requesting the JRC API change.
> 
> No problem waiting a bit, but I like to have a Plan B ready,

?
It's not just you who decides...

As you know because you were in the meeeting, this was already discussed extensively in the last Tech IOP and the general agreement of the group was to have an alternative plan.
As you should also be aware from that same meeting: T-Systems made it very clear that even if we change it here then this will not make it into production as they have a database schema already fixed and approved and rolled-out and that will not be changed at this late stage.
So, yes, this alternative is useful (even necessary, IMHO) so we should have it and be able to present it to T-Systems. 

> for when the API change doesn't come through. And when it does, 

self-contradiction

> it'd still make sense to sort the values by id,

Half-agree. Only makes sense - as Hynek pointed out - for manual comparison.
This process should also be automated.
The shell script update-rat.sh exists, so we can extend with one of two approaches:
1. we stay in shell script land, in which case you would probably be looking at `diff -e` and `sed` together with some shell commands - careful as most universal is the original Bourne shell - `sh` - which e.g. under Linux is typically sym-linked to `dash` - this means that all the nice `bash` shell extensions with variable manipulation are not open to you, OR
2. you write a Python script for the diff patching.
If you are going to write a Python script then still call it from update-rat.sh - makes for a low entry level.
Your two choices here are shell or Python - keeps a low barrier for entry and are fairly universal.

> to make the derivation as stable as possible.

No idea what you mean by this. Could you please clarify?

**Comment by dslmeinte** [comment]
No problem to retract this PR, and come up with a Python script that does the diff patching. (I tried my hand at a jq-based thing, but that's both tricky to get right, hardly understandable, and brittle.)

W.r.t “derivation as stable as possible”: expected differences per update are expected to be small and mostly consist of new values. The diff in `test-manf.json` in this Git repo should reflect that, and not be obfuscated because of differing key orders, so a stable key order helps with that. (Having a stable key order obviously also helps with manual comparison.)

**Comment by gabywh** [comment]
> No problem to retract this PR, and come up with a Python script that does the diff patching. 

+1

> (I tried my hand at a jq-based thing, but that's both tricky to get right,

yes...

> hardly understandable

yes...

and brittle.)

and yes! ;)

> 
> W.r.t “derivation as stable as possible”: expected differences per update are expected to be small

not necessarily, I would hope so, but there's nothing stopping new products being added and old being discounted, even if they are a 1:1 replacement - thus the "churn" (aka delta) is typically bigger than the just the "couple" (which can be quite a few, actually) of new items to be added

> and mostly consist of new values. 

well, new ones added that's for sure, but others will also be discontinued (so again you have more "churn" than just a couple of new entries) ->  this is where e.g. the JRC valid_from / valid_until would be useful, which we work into the active flag, for all the reasons discussed at length here: https://github.com/ehn-dcc-development/ehn-dcc-schema/wiki/FAQ#valuesets

>The diff in `test-manf.json` in this Git repo 

? I see two points possibly not understood here - but rather than go on my assumption, could you please clarify your point(s)?

> should reflect that, and not be obfuscated because of differing key orders, 

Again, this is for manual only, even as the term "obfuscated" also indicates -> directed at a human reader.
An automated diff won't care, it will just do the right thing - so why add unnecessary complication?

> so a stable key order helps with that. 

if `diff` doesn't care, why should you?

> (Having a stable key order obviously also helps with manual comparison.)

Yep, as above - for manual comp only. If you need to do manual comp you can always sort then if you really find you need to...
Target: all of the valuesets should be auto-generated via script.
Prio: the more volatile contents the higher the prio to get it scripted.

**Pull request closed without merging**
