### PR TITLE
Release/2.3.0 merged to main

### PR DESCRIPTION
**Pull request by dslmeinte**
(instead of the release branch for 2.2.0)

### CODE REVIEW

**Review by kruzikh — APPROVED** [review]

**Comment by dslmeinte** [comment]
I think we should merge this PR before merging PR #33. Right after merging PR #33, I'll clean up the release branches accordingly. I just need 1 more approval on this PR (#32).

**Review by skounis — APPROVED** [review]

**Comment by kruzikh** [comment]
@dslmeinte I see wrong release label in Github (it is still 2.2.0).

**Comment by dslmeinte** [comment]
@kruzikh That's actually the reason for the process change: it's too easy that newer works lands on the branch for a prior release, as we found out. So after merging this PR, I'll delete this branch, and tag the correct commits with their release version numbers.

**Comment by dslmeinte** [comment]
Haha, I can't delete release branches, because they're protected, and I don't have admin rights. I also can't change the default branch, for the same reason.

Two solutions: 1) someone makes me admin, or 2) they do these changes themselves.

**Comment by skounis** [comment]
@dslmeinte I set `main` as the default branch and deleted the `release/2.3.0` 

Before we delete anything else we need to give it a second thought, or atleast a bit of time. Other systems may depend on the versioning/releasing schema we had so for and may collapse if we take the `release/2.2.0` out.

**Comment by dslmeinte** [comment]
I think the `release/2.2.0` branch is “misleading” - maybe delete that one as well? We can recreate both 2.2.0 and 2.3.0 release branches at the correct commits (#7b30140e266cc6c24297e319515e27c5a08e701b, #fdff116a58df3066116604865f96982fcf04947e, resp.) anyway.

**Comment by skounis** [comment]
I have the old `release/2.2.0` on my local. Is it ok if I delete the remote and push it again ?

**Comment by dslmeinte** [comment]
> I have the old `release/2.2.0` on my local. Is it ok if I delete the remote and push it again ?

Absolutely!

**Comment by skounis** [comment]
`done`

**Comment by dslmeinte** [comment]
Looks perfect! :)

**Pull request merged**
