### PR TITLE
Update to eHN guidelines document for value sets, version 1.7

### PR DESCRIPTION
**Pull request by dslmeinte**
Closes https://github.com/ehn-dcc-development/ehn-dcc-valuesets/issues/41

### CODE REVIEW

**Comment by dslmeinte** [comment]
But we release the value set only after the adoption has been officially published.

**Review by kruzikh — CHANGES_REQUESTED** [review]
In case of "NVX-CoV2373" the status active should also be changed to false.

**Comment by dslmeinte** [comment]
We could do that, but I'm not sure that that flag actually really means something. Changing this could suggest that it does mean something, e.g. that it's automatically considered invalid, while it really doesn't. We should look into that as well, it seems.

**Comment by molk-ibm** [comment]
`NVX-CoV2373` is _deprecated_ but should remain _active_, as there might be some DCCs already referencing this code.
So _de-activating_ it might do more harm that it helps, right?

The deprecation notice in the display name should be sufficient.

**Comment by kruzikh** [comment]
The idea of the active attribute was from the beginning to allow changes in coding, i.e. deprecation of codes. The meaning of this attribute is similar to any other terminology (e.g. SNOMED CT):
- when true - active concept can be used for generation of new certificates
- when false - inactive concept, that is kept in the valueset to support historical certificates but is not intended for use on new certificates.
It is of course on implementers to use it properly. But, so far I am not aware of any business rule in validation app that would reject certificates that use inactive concepts, so it should be safe to use it and to mark the concept inactive.

**Comment by dslmeinte** [comment]
Commit to that extent = pushed.

**Review by kruzikh — CHANGES_REQUESTED** [review]
Please, could tou also adjust Changelog to reflect changes in "active" attribute?

**Comment by dslmeinte** [comment]
@kruzikh Done (9e3de3d)

**Comment by dslmeinte** [comment]
@kruzikh @skounis @ryanbnl Could someone review and approve this? Then we can merge it, and also start the release process for version 2.5.0.

**Review by skounis — APPROVED** [review]

**Review by kruzikh — APPROVED** [review]

**Pull request merged**
