### PR TITLE
Release/2.7.0

### PR DESCRIPTION
**Pull request by dslmeinte**
On draft until *official* adoption of v1.9 value sets.

### CODE REVIEW

**Comment by kruzikh** [comment]
@dslmeinte,

I cannot review your PR because I don' have access to the Guidelines version 1.9. Could you attach it?

**Comment by ryanbnl** [comment]
Not sure if it's allowed to be published in public, I'll send it to your email!

**Comment by dslmeinte** [comment]
@kruzikh It's public as soon as the document is officially adopted (yesterday) and published at the URL in the change log. Only then can we make this release.

**Comment by dslmeinte** [comment]
The v1.9 version is now published: https://ec.europa.eu/health/sites/default/files/ehealth/docs/digital-green-value-sets_en.pdf

**Review by kruzikh — COMMENTED** [review]
The link to the guidelines v 1.9 in change log should be updated.
Covishield vaccine has version number 1.2 in guidelines - is there any reason why we have version 1.8 in the schema?

**Comment by kruzikh** [comment]
You are right with the link. As regards the version number, it is on line 199 of the vaccine-medicinal-product.json.

**Comment by dslmeinte** [comment]
@kruzikh https://github.com/ehn-dcc-development/ehn-dcc-valuesets/pull/51/files#diff-6cf316cd1ee3769362fcaa9a7981d6cc2ea9d90b7e49d2815e6074e9ea278b27L199 belongs to the Sputnik-M entry, not to Covishield.
Covishield's version number (1.2) is here: https://github.com/ehn-dcc-development/ehn-dcc-valuesets/pull/51/files#diff-6cf316cd1ee3769362fcaa9a7981d6cc2ea9d90b7e49d2815e6074e9ea278b27L101
(It's quite easy to misread GitHub diffs, by the way.)

**Review by kruzikh — APPROVED** [review]

**Review by ryanbnl — APPROVED** [review]

**Pull request merged**
