### PR TITLE
Describe new versioning process.

### PR DESCRIPTION
**Pull request by dslmeinte**
As per the discussion in PR #31 .

### CODE REVIEW

**Review by kruzikh — COMMENTED** [review]
Thank you for describing the release maintenance process. However, I would recommend to add exact order and syntax of git commands that should be used to make all steps.

**Comment by ryanbnl** [comment]
Good point! I think that the GitHub command is "rebase and merge".

`git rebase main
git merge --no-ff`

**Comment by dslmeinte** [comment]
OK, @kruzikh and @ryanbnl : I added explanation to the document. Could you check whether it's sufficient?

**Review by skounis — APPROVED** [review]

**Comment by dslmeinte** [comment]
I think I'd be useful to tag releases with the version number of the value set update (e.g. `vs-1.5` for the latest) as well. That way it's clearer that e.g. a 2.4.0 release only add this versioning process, but doesn't correspond to an update of the eHN value set. (Same goes for other purely technical/process-related changes to this repo.)

Agree?

**Review by kruzikh — APPROVED** [review]
Seems to be detail enough, however clarity of the instructions needs to be tested by some silly GitHub user like me :-)

**Comment by skounis** [comment]
@dslmeinte Do we really need a new release/version for this? 

Technically all the changes we did since `2.2.0` are not released so everything could go into `2.3.0`

**Comment by dslmeinte** [comment]
I think we did release 2.3.0, because we made a 2.3.0 release page. A release is in itself a “cheap” thing: getting updates to the value set document approved is expensive. Personally, I'd rather release more often, than “bunch up” multiple, heterogeneous changes.

**Comment by skounis** [comment]
We didn't inform anyone yet. Hence my comment.

**Comment by dslmeinte** [comment]
I'm fine either. Rolling the changes now merged to `release/2.4.0` into a recreated `release/2.3.0` branch. Let's see what happens?

**Pull request merged**
